spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/public
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true